name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: syedbilal07
          outputs: |
            ./output/github-contribution-grid-snake.svg
      - name: Commit and push if changed
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Action"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation" || echo "No changes to commit"
          git push
